const allITLang = {
    'ABAP': null,
    'ActionScript': null,
    'Ada': null,
    'ALGOL': null,
    'Alice': null,
    'APL': null,
    'ASP / ASP.NET': null,
    'Assembly Language': null,
    'Awk': null,
    'BBC Basic': null,
    'C': null,
    'C++': null,
    'C#': null,
    'COBOL': null,
    'Cascading Style Sheets': null,
    'D': null,
    'Delphi': null,
    'Dreamweaver': null,
    'Erlang and Elixir': null,
    'F#': null,
    'FORTH': null,
    'FORTRAN': null,
    'Functional Programming': null,
    'Go': null,
    'Haskell': null,
    'HTML': null,
    'IDL': null,
    'INTERCAL': null,
    'Java': null,
    'Javascript': null,
    'Node.js': null,
    'Bootstrap': null,
    'jQuery': null,
    'LabVIEW': null,
    'Lisp': null,
    'Logo': null,
    'MetaQuotes Language': null,
    'ML': null,
    'Modula-3': null,
    'MS Access': null,
    'MySQL': null,
    'NXT-G': null,
    'Object-Oriented Programming': null,
    'Objective-C': null,
    'OCaml': null,
    'Pascal': null,
    'Perl': null,
    'PHP': null,
    'PL/I': null,
    'PL/SQL': null,
    'PostgreSQL': null,
    'PostScript': null,
    'PROLOG': null,
    'Pure Data': null,
    'Python': null,
    'R': null,
    'RapidWeaver': null,
    'RavenDB': null,
    'Rexx': null,
    'Ruby on Rails': null,
    'S-PLUS': null,
    'SAS': null,
    'Scala': null,
    'Sed': null,
    'SGML': null,
    'Simula': null,
    'Smalltalk': null,
    'SMIL': null,
    'SNOBOL': null,
    'SQL': null,
    'SQLite': null,
    'SSI': null,
    'Stata': null,
    'Swift': null,
    'Tcl/Tk': null,
    'TeX and LaTeX': null,
    'Unified Modeling Language': null,
    'Unix Shells': null,
    'Verilog': null,
    'VHDL': null,
    'Visual Basic': null,
    'Visual FoxPro': null,
    'VRML': null,
    'WAP/WML': null,
    'XML': null,
    'XSL': null
}

const allITLangArray = Object.keys(allITLang);

export const ITSkills ={
    allITLang: allITLang,
    allITLangArray: allITLangArray
}