const allSpknLang = {
    'Afrikanns': null,
    'Albanian': null,
    'Arabic': null,
    'Armenian': null,
    'Basque': null,
    'Bengali': null,
    'Bulgarian': null,
    'Catalan': null,
    'Cambodian': null,
    'Chinese (Mandarin)': null,
    'Croation': null,
    'Czech': null,
    'Danish': null,
    'Dutch': null,
    'English': null,
    'Estonian': null,
    'Fiji': null,
    'Finnish': null,
    'French': null,
    'Georgian': null,
    'German': null,
    'Greek': null,
    'Gujarati': null,
    'Hebrew': null,
    'Hindi': null,
    'Hungarian': null,
    'Icelandic': null,
    'Indonesian': null,
    'Irish': null,
    'Italian': null,
    'Japanese': null,
    'Javanese': null,
    'Korean': null,
    'Latin': null,
    'Latvian': null,
    'Lithuanian': null,
    'Macedonian': null,
    'Malay': null,
    'Malayalam': null,
    'Maltese': null,
    'Maori': null,
    'Marathi': null,
    'Mongolian': null,
    'Nepali': null,
    'Norwegian': null,
    'Persian': null,
    'Polish': null,
    'Portuguese': null,
    'Punjabi': null,
    'Quechua': null,
    'Romanian': null,
    'Russian': null,
    'Samoan': null,
    'Serbian': null,
    'Slovak': null,
    'Slovenian': null,
    'Spanish': null,
    'Swahili': null,
    'Swedish ': null,
    'Tamil': null,
    'Tatar': null,
    'Telugu': null,
    'Thai': null,
    'Tibetan': null,
    'Tonga': null,
    'Turkish': null,
    'Ukranian': null,
    'Urdu': null,
    'Uzbek': null,
    'Vietnamese': null,
    'Welsh': null,
    'Xhosa': null
}

export const Spokenlang = {
    allSpknLang: allSpknLang
}
